---
- name: Install and Extract the file
  hosts: jenkinsServers
  become: true
  become_user: ubuntu
  tasks:
    - name: Install Apache Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.31/bin/apache-tomcat-10.1.31.tar.gz
        dest: /home/ubuntu
        mode: 0644

    - name: Extract the tar file
      command: tar -zvxf /home/ubuntu/apache-tomcat-10.1.31.tar.gz -C /home/ubuntu
