---
- name: Install a specific version of Maven
  hosts: jenkinsServers
  become: true
  become_user: root
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Install the latest Maven
      apt:
        name: maven
        state: latest
      become: true
      become_user: root
